Entities/Response.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Entities
{
    public class Response
    {
        public int Id { get; set;}
        public int? AuthorId { get; set;}
        public virtual User Author { get; set;}

        public DateTime Date {get; set;}
        public string Content { get; set;}

        public int TopicId { get; set;}
        public virtual Topic Topic { get; set;}
    }
}

Controllers/ResponseController.cs
using Forum.Models;
using Forum.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Controllers
{
    [Route("Category/{categoryid}/Topic/{topicid}/Response")]
    [Authorize]
    public class ResponseController : Controller
    {
        private readonly IResponseService _responseService;
        private readonly ITopicService _topicService;

        public ResponseController(IResponseService responseService, ITopicService topicService)
        {
            _responseService = responseService;
            _topicService = topicService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int topicid, int id)
        {
            var response = _responseService.GetById(topicid, id);
            return View(response);
        }


        [HttpPost("Create")]
        public ActionResult Create(CreateResponseDto dto, int categoryid, int topicid)
        {
            if (ModelState.IsValid)
            {
                var id = _responseService.Create(dto, topicid);
                return View("../Topic/Details", _topicService.GetById(categoryid, topicid));
            }
            return View();
        }

        [HttpGet("Edit/{id}")]
        public ActionResult Edit(int topicid, int? id)
        {
            var reponse = _responseService.GetById(topicid, (int)id);
            return View(reponse);
        }

        // POST: HomeController1/Edit/5
        [HttpPost("EditSave/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditSave(CreateResponseDto dto, int categoryid, int topicid, int id)
        {
            _responseService.Update(dto, topicid, id);
            return View("../Topic/Details", _topicService.GetById(categoryid, topicid));
        }

        [HttpGet("Delete/{id}")]
        public ActionResult Delete(int topicid, int id)
        {
            var reponse = _responseService.GetById(topicid, id);
            return View(reponse);
        }

        // POST: HomeController1/Delete/5
        [HttpPost("DeleteConfirmed/{id}")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int categoryid, int topicid, int id)
        {

            _responseService.Delete(topicid, id);
            return View("../Topic/Details", _topicService.GetById(categoryid, topicid));
        }
    }
}

Controllers/TopicController.cs
using Forum.Entities;
using Forum.Models;
using Forum.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Controllers
{
    [Route("Category/{categoryid}/Topic")]
    [Authorize]
    public class TopicController : Controller
    {
        private readonly ITopicService _topicService;
        public TopicController(ITopicService topicService)
        {
            _topicService = topicService;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int categoryid, int id)
        {
           
            var topic = _topicService.GetById(categoryid, id);
            return View(topic);
        }

        [HttpPost("Create")]
        public ActionResult Create(CreateTopicDto dto, int categoryid)
        {
            if (ModelState.IsValid)
            {
                var id =_topicService.Create(dto, categoryid);
                return View("Details", _topicService.GetById(categoryid, id));
            }
            return View();
        }

        [HttpGet("Edit/{id}")]
        public ActionResult Edit(int categoryid, int? id)
        {
            var topic = _topicService.GetById(categoryid, (int)id);
            return View(topic);
        }

        // POST: HomeController1/Edit/5
        [HttpPost("EditSave/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditSave(CreateTopicDto dto, int categoryid, int id)
        {
            _topicService.Update(dto, categoryid, id);
            return RedirectToAction("Details", "Category", new { id = categoryid });
        }

        // GET: HomeController1/Delete/5
        [HttpGet("Delete/{id}")]
        public ActionResult Delete(int categoryid, int id)
        {
            var topic = _topicService.GetById(categoryid, id);
            return View(topic);
        }

        // POST: HomeController1/Delete/5
        [HttpPost("DeleteConfirmed/{id}")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int categoryid, int id)
        {
            
            _topicService.Delete(categoryid, id);
            return RedirectToAction("Details", "Category", new { id = categoryid });
        }
    }
}

Controllers/UserController.cs
using AutoMapper;
using Forum.Entities;
using Forum.Models;
using Forum.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Controllers
{
    [Authorize(Roles="Admin, Moderator")]
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;
        private readonly ForumDbContext _dbContext;
        private readonly IBlackListService _blackListService;
        // GET: UserController
        public UserController(UserManager<User> userMenager, IMapper mapper, ForumDbContext dbContext, IBlackListService blackListService)
        {
            _userManager = userMenager;
            _mapper = mapper;
            _dbContext = dbContext;
            _blackListService = blackListService;
        }

        // GET: UserController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var user = _dbContext
                .Users
                .Include(t => t.Topics)
                .FirstOrDefault(u => u.Id == id);
            var userDto = _mapper.Map<UserDto>(user);
            return View(userDto);
        }

        public async Task<ActionResult> BanUser(BanUserDto dto)
        {
            
            var user = await _userManager.GetUserAsync(User);
            dto.ModId = user.Id;
           
            return View("BanUser", dto);
        }
        public async Task<ActionResult> BanDetails(BanUserDto dto, int id)
        {
            await _blackListService.BanUser(dto, id);           
            
            return RedirectToAction("Details", new {id});
        }
    }
}

Views/Response/Create.cshtml
@model Forum.Models.CreateResponseDto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>CreateResponseDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Response/Delete.cshtml
@model Forum.Entities.Response

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Response</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Email)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic.Content)
        </dd class>
    </dl>
    
    <form asp-action="DeleteConfirmed" asp-route-id="@Model.Id" asp-route-topicid="@Model.TopicId" asp-route-categoryid="@Model.Topic.CategoryId" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

Views/Response/Details.cshtml
@model Forum.Entities.Response

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Response</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="User" asp-action="Details" asp-route-id="@Model.AuthorId"> @Html.DisplayFor(model => model.Author.UserName) </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic.Content)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Category" asp-action="Details" asp-route-id="@Model.Topic.CategoryId">Back to List</a>
</div>

Views/Response/Edit.cshtml
@model Forum.Entities.Response

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Response</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-action="EditSave" asp-route-id="@Model.Id" asp-route-topicid="@Model.Topic.Id" asp-route-categoryid="@Model.Topic.CategoryId" method="post" type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Topic" asp-action="Details" asp-route-id="@Model.TopicId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}